Fix README mention of non-existing C++ destroy() method
Introduced with 7d93e90a9565a016f5ef65ca810f97a99bf6b44c, README mentions a call to the `destroy()` in the C++ example.
This method does not exist:

```c++
error: ‘class webview::webview’ has no member named ‘destroy’
   36 |     w.destroy();
      |       ^~~~~~~
```